#!/usr/bin/env bash

check_factor() {
    if [ $# -ne 3 ]; then
        args=("$@")
        count=0
        num2=1
        for a in "${args[@]}"; do
            if [ $count -gt 1 ]; then
                num2=$(($a*$num2)) 
            fi
            count=$((count + 1))
        done
    else
        num2=$3
    fi

    num1=$2
    num=$(echo "$1" | tr ':' '=')

    result=$((num2 > num1 ? 1 : 0))
    if [ $result -eq 1 ]; then
        numcp=$num1
        num1=$num2
        num2=$numcp
    fi

    echo "$num$num1*$num2"  
}

while read -r line; do
    result=$(check_factor "$line")
    check_factor $result  
done < "$1"
